name = "PiecewiseLinearOpt"
uuid = "0f51c51e-adfa-5141-8a04-d40246b8977c"
repo = "https://github.com/joehuchette/PiecewiseLinearOpt.jl.git"
version = "0.3.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Cbc = "â‰¥ 0.6.0"
JuMP = "~0.19, ~0.20, 0.21"
MathOptInterface = "~0.8, ~0.9"
julia = "1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Cbc"]
